sudo: required

services:
  - docker

env:
  global:
    - TAGS="15.05.1-ar71xx 17.01-ar71xx 17.01-ramips-mt7620 17.01-bcm53xx"
    - DOCKERHUB_USER=yhnw
    - DOCKERHUB_REPO=openwrt-sdk
    - secure: "eQ3jV1fZlL7pa/ihyEWSJNEJYuFS61M3OIFToFfD4OIxHHS3kjVitYYH2Jd+fMeu5rbRyd4PDHHI0LqkQpwsIX1uLrY0vN/LGfV83lae8bMQLdH+gAfdFXW6uh+sl9KQwwdb0IH20SYHiw71Ya9OAdq/VXtI5s+PROeLfow6i2GuhQjMHCclgmmbLL2H/wzKMogfYBLzIegii8tGkaM37LtSlRtPu7gRJYSdYX9WVLSAobx5RweMtPWHwrUyk7hEX/wm8GEbTt6QbkM+TB6082fDq+GYO/Xyq7o3YB2/nhRYtYCITuj8pEh779QClJGGvtMCoaT5SY9uqNByjUTVH/QRjvpDiDo+48rmU+B748t4ilrjfxQZytrtHy8Yz5f6XRcmrbiZ2jlYI3abDFiBxQYIQvz90y0+q6XtFN/+h1HIDBK4bua6Ry78KyzALC5Mb8RYXkerb0FpHT1Qoxl60hD0KTo/MVgLpq6Evmir4BcxK0SzjDl1XQWOiN08td9R4bB0AdAimvydUmKXwZ36edowdEoP7ReKrJh6oWh75KWuAGPGDXibOyJWmq1ibpiik5AwrH7iLsWpr5jSs6cye7H99VtX6PiMIQJmjFNvCN9vyjzvJLGFzCzyGvKkQfoxtV/RxYfgCyl3hjVsXZ/Pv7ZD1mSznIEzz+ZRUDCj8og="


before_install:
  - docker version
  - docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPO:base -f Dockerfile.base .

script:
  - for TAG in $TAGS; do
      docker build -t $DOCKERHUB_USER/$DOCKERHUB_REPO:$TAG -f Dockerfile.$TAG .;
    done

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u=$DOCKERHUB_USER -p=$DOCKERHUB_PASSWORD &&
      docker push $DOCKER_USER/$DOCKERHUB_REPO ;
    fi
